### ISSUE TITLE
Record live streams in real-time until cancelling

### ISSUE THREAD

**Issue by xymaxim** [xymaxim/ytpb#12]
**Feature description**

Recently, on Reddit, user [u/jamesteed](https://www.reddit.com/user/jamestossed/) [asked](https://www.reddit.com/r/youtubedl/comments/1c3n73v/youtube_livestream_downloader_that_can_go_past_6h/) about downloading a live stream from the start of the command until cancelling and, importantly, recording must be supported for more than six hours (segment base URLs are expired after this time).

It's a nice and demandable feature to add. The recording of an ongoing stream in real-time is not that difficult (given that the retry mechanism has already been implemented; see https://github.com/xymaxim/ytpb/commit/d08ff92a5d5e49406876e8cf377915865b36a39f), but it requires some additional changes (see the task list below).

**Use case**

Usage examples could be as follows:

(a) *With an open interval*

- Record a stream from now until interruption (or the end of a stream):

      $ ytpb download -i now/.. STREAM

- Record a stream from past moments until interruption (or the end of a stream):

      $ ytpb download -i 20240415T1200/.. STREAM

- Record a stream from the beginning, i.e. from the first segment if it's still available (or from the earliest available segment) until interruption (or the end of a stream):

      $ ytpb download -i earliest/.. STREAM

(b) *With a closed interval*

Record a stream from now until some future dates (including ones specified via [durations](https://ytpb.readthedocs.io/en/latest/cli.html#b-using-duration)):

    $ ytpb download -i now/20240416T00+00 STREAM
    $ ytpb download -i now/PT12H STREAM

**Task list**

- [x] Refer to the current moment, i.e. the last available segment ([link](https://ytpb.readthedocs.io/en/latest/cli.html#now-keyword))
- [x] Catch HTTP 403 errors and refresh segment base URLs ([link](https://ytpb.readthedocs.io/en/latest/package/api/ytpb.playback.html#ytpb.playback.PlaybackSession))
- [ ] Specify now as a start point and allow using end points from the future
- [ ] Implement resumable downloading via state files

**Comment by xymaxim** [comment]
Closing this as not planned. As an alternative, see [Kethsar/ytarchive/198](https://github.com/Kethsar/ytarchive/pull/198) for the implemented feature.
